import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./components/Provider";
import { Flowbite } from "flowbite-react";
import { Topbar } from "./components/Topbar";
import { HeaderComponent } from "./components/HeaderComponenet";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Baku's Mod Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <HeaderComponent />
          {children}
        </Providers>
      </body>
    </html>
  );
}
